Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 160
  Exclude:
    - app/admin/*

Style/Documentation:
  Enabled: false

Lint/RaiseException:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Metrics/BlockLength:
  Max: 60
  Exclude:
    - app/admin/*
    - lib/tasks/*

Style/HashEachMethods:
  Enabled: true

Metrics/AbcSize:
  Max: 50
  Exclude:

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Metrics/MethodLength:
  Max: 60

Metrics/ClassLength:
  Max: 120
  Exclude:


Naming/FileName:
  Exclude:
    - config/initializers/rack-attack.rb

AllCops:
  Exclude:
    - db/migrate/*
    - db/schema.rb
    - bin/**/*
    - vendor/**/*
    - log/**/*
    - public/**/*
    - tmp/**/*
    - assets/**/*
    - coverage/**/*
    - node_modules/**/*

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15
