name: Run Rubocop Brakeman  RSpec(Without System Spec)
run-name: CI
on:
  push:
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      TZ: Asia/Tokyo
      DB_HOST: localhost
      DB_USER: postgres
      DB_PASSWORD: password
      RAILS_ENV: test
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
        ports:
          - 5432:5432
        volumes:
          - postgres_volume:/var/lib/postgresql/data
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .tool-versions
          bundler-cache: true
      - uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
          cache: 'yarn'
      - name: Setup Rails
        run: |
          bin/rails db:migrate:reset
          # bundle exec rake assets:precompile
      - name: Run Rubocop
        run: |
          bundle exec rubocop app lib spec
      - name: Run ERB-Lint
        run: |
          bundle exec erblint --lint-all
      - name: Run Brakeman
        run: |
          bundle exec brakeman --no-pager
      - name: Run RSpec
        run: |
          bundle exec rspec --exclude-pattern "spec/system/**/*_spec.rb"
