name: Run RSpec(System Spec)
run-name: CI
on:
  push:
    pull_request: {}
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      TZ: Asia/Tokyo
      DB_HOST: localhost
      DB_USER: ci
      DB_PASSWORD: password
      RAILS_ENV: test
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ci
          POSTGRES_PASSWORD: password
        ports:
          - 54322:5432
        volumes:
          - postgres_volume:/var/lib/postgresql/data
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .tool-versions
          bundler-cache: true
      - uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
          cache: 'yarn'
      - name: Setup Rails
        run: |
          bin/rails db:migrate:reset
          bundle exec rake assets:precompile
      - name: Install chrome
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt update -y
          sudo apt install -y google-chrome-stable
      - name: Run RSpec
        run: |
          bundle exec rspec spec/system
      - name: Archive Screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: tmp/capybara/
